# Generated by Django 5.2.6 on 2025-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
