# Generated by Django 5.2.6 on 2025-09-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_usercode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Ad',
            new_name='ad',
        ),
    ]
