# Generated by Django 5.2.6 on 2025-09-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_rename_ad_comment_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'на рассмотрении'), ('accept', 'принят'), ('reject', 'отклонен')], default='pending', max_length=20),
        ),
    ]
