# Generated by Django 5.2.6 on 2025-09-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_n_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='N',
        ),
    ]
