# Generated by Django 5.2.6 on 2025-09-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_delete_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
